# Site settings
title: Test, Develop & Automate
header-img: img/home-bg.jpg
email: juperala(at)dnainternet.net
copyright_name: Juho Perälä
description: "Test, develop, automate"
baseurl: ""
url: "https://jperala.fi"
twitter_username: juperala
#github_username:  juperala
#facebook_username: juho.perala
#email_username:  juperala (at) dnainternet.net
linkedin_username: in/juperala

# Google Analytics
google_tracking_id: UA-44856723-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
