# Site settings
title: juperala.fi
header-img: img/home-bg.jpg
email: juperala(at)dnainternet.net
copyright_name: Juho Perälä
description: "Test, develop, automate"
baseurl: ""
url: "http://juperala.github.io"
twitter_username: juperala
#github_username:  juperala
#facebook_username: juho.perala
email_username:  juperala (at) dnainternet.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
