# Site settings
title:            jperala.fi
#email:            juperala(at)dnainternet.net
description:      "Test, develop, automate"
author:           "Juho Perälä"
baseurl:          ""
url:              "https://jperala.fi"

# Social Profiles
twitter_username:   juperala
github_username:   juperala
#facebook_username: juho.perala
linkedin_username: in/juperala

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
